export const SIGNALING_CONNECTED = "SIGNALING_CONNECTED";
export const RECONNECTING = "RECONNECTING";
export const CHAT_MESSAGE = 'CHAT_MESSAGE';
export const WS_READY = 'WS_READY';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';